# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc18dc4a55a653d4d1b3fd7ca284a1a94d80f60c4d5326db397405deac0d94e805c053c9772779fc802ad997829c17912222fcbc43842dea04ba8f3c7a32dd29

test:
  secret_key_base: 31f81a3de6a4c03606183a11f5e55aeb991f2a22c8fac4461ce03c99f6e36d75835929c93d5e57dd99e9b79bd2c3b85ebc8797d60b3b22b7d1bf8ac2a30d5790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
